In [4]:
from tkinter.font import names

import pandas as pd
import numpy as np
from debugpy.common.timestamp import current

In [18]:
df = pd.read_csv("../data/raw_data/meta1.csv")

In [19]:
df

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION,Unnamed: 8
0,0-20000-0-11406,L3CHEB01,1863-10-01T00:00Z,1919-12-31T23:59Z,Cheb,12.362892,50.076212,458.0,NaN
1,0-20000-0-11406,L3CHEB01,1933-05-07T00:00Z,1938-04-30T23:59Z,Cheb,12.388900,50.073900,471.0,NaN
2,0-20000-0-11406,L3CHEB01,1943-06-01T00:00Z,1945-01-31T23:59Z,Cheb,12.388900,50.073900,471.0,NaN
3,0-20000-0-11406,L3CHEB01,1951-01-01T00:00Z,1960-12-31T23:59Z,Cheb,12.388900,50.073900,471.0,NaN
4,0-20000-0-11406,L3CHEB01,1961-01-01T00:00Z,2000-12-31T23:59Z,Cheb,12.388900,50.073900,471.0,NaN
...,...,...,...,...,...,...,...,...,...
5485,0-203-0-42109005002,B1STHR01,1980-01-01T00:00Z,3999-12-31T23:59Z,Starý Hrozenkov,17.861400,48.968100,412.0,NaN
5486,0-203-0-42109007001,B1PITI01,1944-10-01T00:00Z,1961-12-31T23:59Z,Pitín,17.890500,49.000900,342.0,NaN
5487,0-203-0-42109026001,B1LOPE01,1902-01-01T00:00Z,1902-12-31T23:59Z,Lopeník,17.792800,48.945800,672.0,NaN
5488,0-203-0-42109026001,B1LOPE01,1936-03-15T00:00Z,1946-06-30T23:59Z,Lopeník,17.792800,48.945800,672.0,NaN
5489,0-203-0-42109026001,B1LOPE01,1988-08-01T00:00Z,1990-04-30T23:59Z,Lopeník,17.787500,48.940600,655.0,NaN

In [ ]:
names = df["FULL_NAME"].str.contains("Praha",regex=True)

In [26]:
names = df["FULL_NAME"].str.contains("Praha",regex=True)
df = df[names]
df = df["END_DATE"] > pd.Timestamp.now(tz="utc")

TypeError: Invalid comparison between dtype=str and Timestamp

In [17]:
df["END_DATE"] = pd.to_datetime(df["END_DATE"],errors="coerce",format="mixed",dayfirst=True)

df = df[names]

print(names.sum())
df = df["END_DATE"] > pd.Timestamp.now(tz="utc")
df

41

58      False
59      False
60      False
61       True
62      False
63      False
64       True
65      False
66      False
67       True
72      False
73      False
74       True
434     False
1077    False
1078    False
1079     True
1389     True
1390    False
1394    False
1395    False
1396    False
1397     True
1398    False
1399     True
1400    False
1401    False
1402    False
1403     True
1404    False
1408    False
1409     True
2032    False
2180    False
2181    False
2182    False
2183     True
2184    False
2185    False
2186     True
2332    False
Name: END_DATE, dtype: bool

In [47]:
print(len(df[date]))

12

In [50]:
df = df[date]

In [60]:
list_of_WSI = df["WSI"].to_list()
list_of_WSI

['0-20000-0-11518',
 '0-20000-0-11519',
 '0-20000-0-11520',
 '0-20000-0-11567',
 '0-203-0-10904013001',
 '0-203-0-11105048001',
 '0-203-0-11201020001',
 '0-203-0-11201020003',
 '0-203-0-11201024001',
 '0-203-0-11202007001',
 '0-203-0-11514',
 '0-203-0-11515']

In [51]:
df

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION,Unnamed: 8
61,0-20000-0-11518,P1PRUZ01,2000-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Ruzyně,14.255556,50.100278,364.00,NaN
64,0-20000-0-11519,P1PKAR01,2024-09-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Karlov,14.427778,50.069167,260.50,NaN
67,0-20000-0-11520,P1PLIB01,2018-05-17T00:00Z,3999-12-31 23:59:00+00:00,Praha Libuš,14.446944,50.007778,302.04,NaN
74,0-20000-0-11567,P1PKBE01,2010-10-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Kbely,14.538056,50.123333,284.50,NaN
1079,0-203-0-10904013001,P1PKOM01,2017-12-07T12:00Z,3999-12-31 23:59:00+00:00,Praha Komořany,14.406360,49.988600,213.00,NaN
1389,0-203-0-11105048001,P1PZKO01,1961-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Zadní Kopanina,14.317800,50.007200,330.00,NaN
1397,0-203-0-11201020001,P1PVIN01,2019-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Vinohrady - Flora,14.461860,50.075840,280.00,NaN
1399,0-203-0-11201020003,P1PCHO01,1997-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Chodov,14.500000,50.029400,297.00,NaN
1403,0-203-0-11201024001,P1PBRE01,2013-09-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Břevnov,14.352689,50.080843,355.00,NaN
1409,0-203-0-11202007001,P1PSUC01,1961-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Suchdol,14.390600,50.143600,268.00,NaN
2183,0-203-0-11514,P1PKLE01,2023-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Klementinum,14.416923,50.086634,190.70,NaN
2186,0-203-0-11515,P1PKLM01,2023-01-01T00:00Z,3999-12-31 23:59:00+00:00,Praha Klementinum,14.416436,50.086341,190.70,NaN